name: Vanillabosses
version: '${project.version}'
main: me.shreb.vanillabosses.Vanillabosses
api-version: 1.16
description: A plugin which naturally spawns bosses to fight in your world!

commands:
  vbAdmin:
    description: Commands for admins of servers to check on the plugin and get important information in order to configure it
    usage: /<command> <respawningBoss/bossinfo/giveItem/specialItem/spawnboss>
  vbInfo:
    description: Commands for the handling of items. This includes a give command, a info command and a refresh command for old items
    usage: /<command> <BossType/info/bosslist/itemlist>
  vbUtil:
    description: Utility commands for the Vanilla Bosses plugin
    usage: /<command> replaceItems
permissions:
  vbAdmin:
    description: Allows you to use /vbAdmin commands
    default: op
  vbUtil:
    description: Allows you to use /vbUtil replaceItems
    default: true
  vbInfo:
    description: Allows you to use /vbInfo <BossType/info/bosslist/itemlist> commands
    default: true