name: Vanillabosses
version: '${project.version}'
main: me.shreb.vanillabosses.Vanillabosses
api-version: 1.16
description: A plugin which naturally spawns bosses to fight in your world!

commands:
  vbAdmin:
    description: Commands for admins of servers to check on the plugin and get important information in order to configure it
    usage: /<command> <respawningBoss>|<bossInfo>